c_stdlib_version:          # [osx]
  - "11.0"                # [osx]
MACOSX_SDK_VERSION:          # [osx]
  - "11.0"                # [osx]
c_stdlib:  # [osx]
  - macosx_deployment_target  # [osx]
channel_targets:
  - conda-forge pdal_rc
