{% set version = "2.6.2" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: 4ec3d128af4d15924ddac91ddac56335cf32897c743349460cfa41d51f0f9e4e

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config

  host:
    - libgdal
    - geotiff
    - libpq
    - libkml
    - eigen
    - nitro
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
    - ceres-solver
    - mkl  # [win]
    - blas  # [win]

  run:
    - libgdal
    - geotiff
    - libpq
    - libkml
    - eigen
    - nitro
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
    - ceres-solver
    - mkl  # [win]
    - blas  # [win]

  run_constrained:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
