{% set version = "2.0.1" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{version}}/PDAL-{{version}}-src.tar.bz2
  sha256: d1e2d5bf031345ed585e340a3bc01100a53955ce0f885c4dfb0345bd2a0fe40a
  patches:
    - apps.patch
    - e57.patch

build:
  number: 7
  skip: True  # [(win and vc<14) or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - numpy
    - libgdal
    - geos
    - geotiff
    - postgresql
    - jsoncpp
    - libkml
    - eigen
    - sqlite
    - laz-perf
    - nitro
    - laszip
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - xerces-c
  run:
    - python
    - numpy
    - jsoncpp
    - postgresql
    - laz-perf
    - geotiff
    - laszip
    - hdf5
    - geos
    - libgdal
    - {{ pin_compatible('numpy') }}
    - nitro
    - curl
    - zlib
    - tiledb
    - zstd
    - libxml2
    - xerces-c

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL)'
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
