{% set name = "pdal" %}
{% set version = "1.7.2" %}
{% set sha256 = "f5dd28c7f25bcd13c460a845860eded67446f3abb6b6a2e2f394a776ad03428a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://download.osgeo.org/{{ name }}/PDAL-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}
  patches:
    - geos.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - numpy
    - libgdal
    - geos
    - postgresql 10.3.*
    - jsoncpp
    - eigen 3.3.*
    - sqlite
    - laz-perf 1.1.*
    - nitro <2.8
    - hexer 1.4.*
    - laszip 3.2.*
    - curl
    - zlib
    - pcl 1.8.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('jsoncpp', max_pin='x.x.x') }}
    - {{ pin_compatible('postgresql', max_pin='x.x') }}
    - {{ pin_compatible('laz-perf', max_pin='x.x') }}
    - {{ pin_compatible('nitro', max_pin='x.x') }}
    - {{ pin_compatible('hexer', max_pin='x.x') }}
    - {{ pin_compatible('laszip', max_pin='x.x') }}
    - {{ pin_compatible('pcl', max_pin='x.x') }}
    - libgdal
    - geos
    - curl
    - zlib

test:
  commands:
    - pdal --version
    - pdal --drivers

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL)'
  description: |
    Point cloud data processing.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
