{% set version = "2.5.6" %}

package:
  name: pdal-split
  version: {{ version }}

source:
  git_url: https://github.com/PDAL/PDAL.git
  git_rev: master
  git_depth: 1 # (Defaults to -1/not shallow)


build:
  number: 2


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config

  host:
    - libgdal
    - geotiff
    - curl
    - zlib
    - zstd
    - libxml2
    - openssl


  run:
    - libgdal
    - geotiff
    - curl
    - zlib
    - zstd
    - libxml2
    - openssl

outputs:
  - name: libpdal
    script: install_lib.sh  # [unix]
    script: install_lib.bat  # [win]
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libpdal', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
        - pkg-config
      host:
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
        - geotiff
        - curl
        - zlib
        - zstd
        - libxml2
        - openssl
      run:
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
        - geotiff
        - curl
        - zlib
        - zstd
        - libxml2
        - openssl
      run_constrained:   # [osx and x86_64]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    test:
      files:
        - test_libpdal.sh  # [unix]
      commands:
        - sh test_libpdal.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt


  - name: pdal-trajectory
    script: build_trajectory.sh  # [unix]
    script: build_trajectory.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - ceres-solver
        - mkl  # [win]
        - blas  # [win]
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
      run:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
        - ceres-solver
        - mkl  # [win]
        - blas  # [win]
    test:
      files:
        - test_trajectory.sh  # [unix]
      commands:
        - sh test_trajectory.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt

  - name: pdal-hdf
    script: build_hdf.sh  # [unix]
    script: build_hdf.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - hdf5
      run:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - hdf5
    test:
      files:
        - test_hdf.sh  # [unix]
      commands:
        - sh test_hdf.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt


  - name: pdal-draco
    script: build_draco.sh  # [unix]
    script: build_draco.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - draco
      run:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - draco
    test:
      files:
        - test_draco.sh  # [unix]
      commands:
        - sh test_draco.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt

  - name: pdal-tiledb
    script: build_tiledb.sh  # [unix]
    script: build_tiledb.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
        - tiledb
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
      host:
        - {{ pin_subpackage('libpdal') }}
      run:
        - {{ pin_subpackage('libpdal') }}
        - {{ pin_compatible('tiledb', max_pin='x.x') }}
        - {{ pin_compatible('libgdal', max_pin='x.x') }}
    test:
      files:
        - test_tiledb.sh  # [unix]
      commands:
        - sh test_tiledb.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt

  - name: pdal-pgpointcloud
    script: build_pgpointcloud.sh  # [unix]
    script: build_pgpointcloud.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
      host:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - libpq
      run:
        - {{ pin_subpackage('libpdal', exact=True) }}
        - libpq
    test:
      files:
        - test_pgpointcloud.sh  # [unix]
      commands:
        - sh test_pgpointcloud.sh  # [unix]
    about:
      summary: Point Data Abstraction Library (PDAL)
      license: BSD-3-Clause
      license_file: LICENSE.txt


about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
