{% set version = "2.3.0" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: 63d8d4fee491675f0fa3dca58c26d57fb2afcaa37c24b10f595b3fbff174996e
  patches:
    - dimbuilder.patch
    - unmap.patch

build:
  number: 17
  skip: true  # [(win and vc<14) or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config
    - libgdal
    - geotiff
    - libpq
    - jsoncpp
    - libkml
    - eigen
    - nitro
    - laszip
    - laz-perf
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
  host:
    - libgdal
    - geotiff
    - libpq
    - jsoncpp
    - libkml
    - eigen
    - nitro
    - laszip
    - laz-perf
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
  run:
    - libgdal
    - geotiff
    - libpq
    - jsoncpp
    - libkml
    - eigen
    - nitro
    - laszip
    - laz-perf
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
