{% set name = "pdal" %}
{% set version = "1.8.0" %}
{% set sha256 = "1d88c96b9407396be22c9ebf564023feb82d65456b5666ecd50b0e7ea5f75ab0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://github.com/PDAL/PDAL/releases/download/{{version}}/PDAL-{{version}}-src.tar.bz2

  sha256: {{ sha256 }}
  patches:
    - geos.patch
    - hdf5.patch
    - pcl.patch

build:
  number: 4
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - numpy
    - libgdal=2.3.*
    - geos
    - geotiff
    - postgresql 10.3.*
    - jsoncpp
    - libkml
    - eigen 3.3.*
    - sqlite
    - laz-perf 1.2.*
    - nitro <2.8
    - hexer 1.4.*
    - laszip 3.2.*
    - curl
    - zlib
    - pcl 1.8.*
    - hdf5
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('jsoncpp', max_pin='x.x.x') }}
    - {{ pin_compatible('postgresql', max_pin='x.x') }}
    - {{ pin_compatible('laz-perf', max_pin='x.x') }}
    - {{ pin_compatible('geotiff', max_pin='x.x') }}
    - {{ pin_compatible('nitro', max_pin='x.x') }}
    - {{ pin_compatible('libkml', max_pin='x.x') }}
    - {{ pin_compatible('hexer', max_pin='x.x') }}
    - {{ pin_compatible('laszip', max_pin='x.x') }}
    - {{ pin_compatible('pcl', max_pin='x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
    - {{ pin_compatible('geos', max_pin='x.x') }}
    - {{ pin_compatible('libgdal', max_pin='x.x') }}
    - curl
    - zlib

test:
  commands:
    - pdal --version
    - pdal --drivers

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL)'
  description: |
    Point cloud data processing.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
