{% set version = "1.9.0" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{version}}/PDAL-{{version}}-src.tar.bz2
  sha256: 7b7f37ae018e9350b1f3fb7604bb0bf11ddff812a4c95cf68b6363da2dcdbd09
  patches:
    - pcl.patch
    - apps.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - numpy
    - libgdal
    - geos
    - geotiff
    - postgresql
    - jsoncpp
    - libkml
    - eigen
    - sqlite
    - laz-perf
    - nitro
    - laszip
    - curl
    - zlib
    - pcl
    - hdf5
  run:
    - python
    - numpy
    - jsoncpp
    - postgresql
    - laz-perf
    - geotiff
    - laszip
    - pcl
    - hdf5
    - geos
    - libgdal
    - {{ pin_compatible('numpy') }}
    - nitro
    - curl
    - zlib

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL)'
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
