{% set version = "2.4.3" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: 3d2b00e87d177f6d01fee3dd3436cd9fc1f6d821fae40f36dccc07469d0d8226

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - libgdal
    - geotiff
    - libpq
    - libkml
    - eigen
    - nitro
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
    - openssl
  run:
    - libgdal
    - geotiff
    - libpq
    - libkml
    - eigen
    - nitro
    - curl
    - zlib
    - hdf5
    - tiledb
    - zstd
    - libxml2
    - draco
    - openssl
  run_constrained:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL)
  description: Point cloud data processing.
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
