schema_version: 1

context:
  version: "2.10.1"

package:
  name: pdal
  version: ${{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/${{ version }}/PDAL-${{ version }}-src.tar.bz2
  sha256: 78765f1d06584c8e9b3b4a5b58c0ebea478d42ad21f1432717b31c20def05522

build:
  number: 0
  noarch: generic

requirements:
  build:
  host:
  run:
    - libpdal 2.10.0.*
    - python-pdal
  run_exports:
    - ${{ pin_subpackage('pdal', upper_bound='x.x') }}

tests:
  - script:
      - pdal --version
      - pdal --drivers --debug

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) meta package
  description: Point cloud data processing library meta package
  homepage: https://www.pdal.io
  repository: https://github.com/pdal/pdal
  documentation: https://pdal.io

extra:
  recipe-maintainers:
    - chambbj
    - hobu
