travis:
  secure:
    BINSTAR_TOKEN: VCQutd8xvcuqmIV7r8xTbEyLPSXPhExM9xfbVUMu8nDN4HEGvVjDwML6EskCdm2ZpF/kf/hEU92EGb7XMP7wVw9Rkdac0jcytP/e8FahN2nG32UB03M63XWgYTya41AKiQ/TVwiMwQ1HZAxXoETBwmUBf2sDmUT7+a5oxazcJQ+G99YRwOJ47CBsRmPTe52kkubYFMxHvkiMe16zMs7ciOAr/UXIKmv1XnNSRM1GCpvdjMBrSoLFzU+e4UomohCxhitTFP/AVPlqf6UsUKj7mzbneIaGONM0ztN4y+CJyJ32DxGfw6tAe04Syac43tFzQ86j7DIGLpZBduk6npEa4OIC6q6p/vHqO+S6o0ThuQuder8ZAeGaT47UAeghJguf/1oJlt8P2eKffA8iSj0HAIZJbuExyBVAQzFKZ43b9cLxcSRCMXKLe/mLqjeoewGpQCH19H70jx/SjG5rMuggx/riZpas09fGaX1lY9fq3IFJ5VwYVVOHDmRoDUTc00BC8K+e08yL2G8tqHt1ad1q+WVLF0Z0FzlM+LvXCR9x3ecR6y4Ak/6Y5CgF2puR8b+nZocb6h2SS4fGq4iVRkLyJW8otvsO8ftYxwSWitGPoQnG4juzREtZ/rdjxyoEXuRwVRNhBK3noGjtQYCl649zRQRQk+TwYXdcUZULAl58cyk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
